### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rmurphey** [Nanonid/rison#1]
Can you add a license to this project? That would let us use it at work much more easily :)

**Comment by Nanonid** [comment]
I forked this from a dead link. Do you still need a license?
Are you using Rison techniques now?

**Comment by Hronom** [comment]
@Nanonid Elasticsearch use Rison for generating embedding link in Kibana https://github.com/elastic/kibana/issues/6663#event-603170037

**Comment by Nanonid** [comment]
I believe the current LICENSE.md resolves this. Please reopen if not.
