### ISSUE TITLE
bower project

### ISSUE THREAD

**Issue by mattgodbolt** [Nanonid/rison#13]
It would be super awesome to have this in `bower` so it can be listed as a dependency there. AFAICT this would need an appropriate `bower.json` and then someone to register the package (as per https://bower.io/docs/creating-packages/ ).

**Comment by Nanonid** [comment]
After some testing, I'll mark this as closed. Thanks Matt.

**Comment by lennerd** [comment]
Whats the status here?

**Comment by Nanonid** [comment]
Registered.
#>bower info rison
bower rison#\*               not-cached https://github.com/Nanonid/rison.git#*
bower rison#\*                  resolve https://github.com/Nanonid/rison.git#*
bower rison#\*                 checkout master
bower rison#\*                 resolved https://github.com/Nanonid/rison.git#f9dc6a4dbf

{
  name: 'rison',
  description: 'URI friendly encoding for JSON structures',
  main: 'js/rison.js',
  authors: [
    'Metaweb Technologies developers@freebase.com'
  ],
  license: 'MIT',
  keywords: [
    'rison'
  ],
  homepage: 'https://github.com/Nanonid/rison',
  ignore: [
    '*_/._',
    'python',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

**Comment by mattgodbolt** [comment]
Thanks!
