### ISSUE TITLE
Main URL dead

### ISSUE THREAD

**Issue by johsin18** [Nanonid/rison#3]
http://mjtemplate.org/examples/rison.html is a dead link.

Are you aware of that (is this the whole reason for this repo), or is this fact new?

**Comment by finom** [comment]
+1
Can you move this HTML page to somewhere else?

**Comment by Nanonid** [comment]
This repo was created to give a home to a great idea, and not let it die.

**Comment by Nanonid** [comment]
The original HTML page is effectively saved here. Reopen with specific issue to resolve. ty
